package it.daniele.business;

public enum Type {

	VIDEOGIOCO_DI_SCACCHI, SCAPPA_DALLA_STANZA, SERIOUS_GAME, VIDEOGIOCO_PORNOGRAFICO, SHOOT_EM_UP,
	VIDEOGIOCO_DI_SIMULAZIONE, SIMULATORE_DI_GUIDA, SIMULATORE_DI_SOTTOMARINI, SIMULATORE_DI_VITA, SIMULATORE_DI_VOLO,
	SPARATUTTO, SPARATUTTO_CON_PISTOLA_OTTICA, SPARATUTTO_IN_PRIMA_PERSONA, SPARATUTTO_IN_TERZA_PERSONA,
	SPARATUTTO_TATTICO, VIDEOGIOCO_SPORTIVO, VIDEOGIOCO_SPORTIVO_MANAGERIALE, VIDEOGIOCO_STEALTH,
	VIDEOGIOCO_STRATEGICO_A_TURNI, VIDEOGIOCO_STRATEGICO_IN_TEMPO_REALE, SURVIVAL_HORROR,

}
